# Generated by Django 3.2 on 2021-05-10 03:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_communityguidelines_howitworks_privacypolicy_quotes_termscondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityguidelines',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='howitworks',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='termscondition',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
