# Generated by Django 3.2 on 2021-05-03 09:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='sd'),
            preserve_default=False,
        ),
    ]
