# Generated by Django 3.2 on 2021-05-05 13:48

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_auto_20210503_1307'),
        ('blog', '0005_auto_20210504_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags. Example: TagOne, TagTwo', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
