# Generated by Django 3.2 on 2021-05-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postview',
            name='user',
        ),
        migrations.AddField(
            model_name='postview',
            name='ip',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
