# Generated by Django 3.2 on 2021-05-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210510_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='updated',
        ),
    ]
