# Generated by Django 3.2 on 2022-01-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_like_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
