# Generated by Django 3.2 on 2022-01-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_author_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
