# Generated by Django 3.2 on 2021-05-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
