# Generated by Django 3.2 on 2021-05-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_followers_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='mark',
        ),
    ]
